/**
 * Audit findings R-07 / F-03 — the fabricated-data marker these pages lacked.
 *
 * `/webhooks` and `/system` are operational surfaces: an on-call engineer reads
 * them during an incident to decide what is broken. Both render seven invented
 * deliveries (`whk_seed_1` … `whk_seed_7`) alongside genuine callback traffic,
 * including terminal statuses — DUPLICATED, REJECTED — for events that never
 * arrived. The global `TestModeBanner` says the deployment is in test mode; it
 * does not say which *rows* were never observed, and that is the distinction that
 * matters when you are counting failures.
 *
 * Render this on any page whose figures can be seed data, and pass the counts so
 * the reader can see how much of what they are looking at is real. It renders
 * nothing when there is no seed data, so a deployment that has real traffic only
 * is not carrying a warning it does not need.
 */
export function DemoDataNotice({
  seeded,
  total,
  scope = "rows on this page",
}: {
  /** How many displayed rows were invented by the store's seed function. */
  seeded: number;
  /** How many rows are displayed in total. */
  total: number;
  /** What the counts refer to, e.g. "callbacks in the last 24 hours". */
  scope?: string;
}) {
  if (seeded <= 0) return null;

  const all = total > 0 && seeded >= total;

  return (
    <div
      role="note"
      aria-label="Demo data"
      data-testid="demo-data-notice"
      className="flex items-start gap-3 rounded-lg border border-[var(--test-mode-amber)]/30 bg-[var(--test-mode-amber)]/10 p-4"
    >
      <span
        className="material-symbols-outlined mt-0.5 shrink-0 text-[20px] text-[var(--test-mode-amber)]"
        aria-hidden="true"
      >
        science
      </span>
      <div className="space-y-1">
        <p className="label-caps text-[var(--test-mode-amber)]">Demo data — not observed traffic</p>
        <p className="body-sm text-[var(--on-surface)]">
          {all
            ? `Every one of the ${total} ${scope} shown here was generated by this deployment's seed data.`
            : `${seeded} of the ${total} ${scope} shown here were generated by this deployment's seed data, not received from a provider.`}{" "}
          Seeded rows are marked <span className="data-mono text-[11px]">seed</span>. Their statuses — including
          duplicated and rejected — describe events that never arrived, so do not use these figures to diagnose an
          incident or to report provider health.
        </p>
      </div>
    </div>
  );
}

/**
 * The row-level provenance marker the notice refers to. Rendered next to a
 * seeded delivery so the two kinds of row are distinguishable in a table, not
 * just in aggregate.
 */
export function SeedBadge() {
  return (
    <span
      data-testid="seed-badge"
      title="Generated by this deployment's seed data — never received from a provider"
      className="data-mono inline-flex shrink-0 items-center rounded border border-[var(--test-mode-amber)]/40 bg-[var(--test-mode-amber)]/10 px-1 py-px text-[10px] leading-none text-[var(--test-mode-amber)]"
    >
      seed
    </span>
  );
}
